const ford = [
  {
    id: 1,
    name: "Ford Bronco",
    price: "P4,998,000 - P5,018,000",
    logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
    image:
      "https://d1hv7ee95zft1i.cloudfront.net/custom/car-model-photo/standard/ford-bronco-outer-banks-with-sasquatch-package-primary-663c43028f443.jpg",
    bodyType: "SUV",
    variants: {
      variant: "2.7L EcoBoost",
      tier: "1",
      bodyType: "SUV",
      price: "₱4.998 Million",
      logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
      dimensions: {
        frontTread: "",
        rearTread: "",
        length: "4811 mm",
        width: "2190 mm",
        height: "1854 mm",
        wheelBase: "2950 mm",
        numberOfDoors: "5",
      },
      capacity: {
        fuelTank: "",
        seatingCapacity: "5 seats",
        payload: "",
      },
      engine: {
        type: "2.7L Gasoline Engine, 6 Cylinder 24 Valve",
        numberOfCylinders: "6",
        valveConfiguration: "",
        fuelSupplySystem: "",
        valvesPerCylinder: "4",
      },
      performance: {
        fuelType: "Gasoline",
        power: "330 hp",
        rpmAtMaxPower: "5750 RPM",
        engineDisplacement: "2698 cc",
        torque: "555 Nm",
        rpmAtMaxTorque: "3000 RPM",
      },
      steering: {
        powerSteering: "Yes",
        steeringColumn: "Tilt & Telescopic",
        steeringGearType: "Rack & Pinion",
        adjustableSteeringColumn: "Yes",
        steeringType: "Electric Power",
      },
      suspension: {
        front: "Stability Suspension",
        rear: "Stability Suspension",
        shockAbsorbersType: "",
      },
      brakes: {
        front: "Discs",
        rear: "Discs",
      },
      transmission: {
        type: "Automatic",
        driveType: "4x4",
        gearBox: "10-Speed",
        steeringWheelGearshiftPaddle: "",
      },
      wheels: {
        alloyWheels: "Yes",
        wheelCovers: "No",
        alloyWheelSize: "17 Inch",
        wheelSize: "R17",
        spareTyreMaterial: "",
      },
      tyres: {
        size: "315/70 R17",
        type: "Radial",
        spareTyreSize: "",
      },
    },
  },
  {
    id: 2,
    name: "Ford Everest",
    price: "P1,829,000 - P2,570,000",
    logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
    image:
      "https://d1hv7ee95zft1i.cloudfront.net/custom/car-model-photo/standard/next-gen-2023-ford-everest-62e21bcfe287e.jpg",
    bodyType: "SUV",
    variants: [
      {
        variant: "2.0L Turbo Trend 4x2 AT",
        tier: "1",
        bodyType: "SUV",
        price: "₱1.829 Million",
        logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
        dimensions: {
          frontTread: "1620 mm",
          rearTread: "1620 mm",
          length: "4904 mm",
          width: "2201 mm",
          height: "1884 mm",
          wheelBase: "2900 mm",
          numberOfDoors: "5",
        },
        capacity: {
          fuelTank: "80 L",
          seatingCapacity: "7 seats",
          payload: "",
        },
        engine: {
          type: "2.0L Diesel Engine, 4 Cylinder 16 Valve",
          numberOfCylinders: "4",
          valveConfiguration: "",
          fuelSupplySystem: "",
          valvesPerCylinder: "4",
        },
        performance: {
          fuelType: "Diesel",
          power: "168 hp",
          rpmAtMaxPower: "3500 RPM",
          engineDisplacement: "1996 cc",
          torque: "405 Nm",
          rpmAtMaxTorque: "1750-2500 RPM",
        },
        steering: {
          powerSteering: "Yes",
          steeringColumn: "Adjustable",
          steeringGearType: "Rack & Pinion",
          adjustableSteeringColumn: "Yes",
          steeringType: "Electric Power",
        },
        suspension: {
          front: "Standard Duty",
          rear: "Standard Duty",
          shockAbsorbersType: "",
        },
        brakes: {
          front: "Ventilated Discs",
          rear: "Ventilated Discs",
        },
        transmission: {
          type: "Automatic",
          driveType: "4x2",
          gearBox: "6-Speed",
          steeringWheelGearshiftPaddle: "",
        },
        wheels: {
          alloyWheels: "Yes",
          wheelCovers: "No",
          alloyWheelSize: "18 Inch",
          wheelSize: "R18",
          spareTyreMaterial: "",
        },
        tyres: {
          size: "255/65 R18",
          type: "Radial",
          spareTyreSize: "",
        },
      },
      {
        variant: "2.0L Turbo Sport 4x2 AT",
        tier: "2",
        bodyType: "SUV",
        price: "₱2.139 Million",
        logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
        dimensions: {
          frontTread: "1620 mm",
          rearTread: "1620 mm",
          length: "4904 mm",
          width: "2201 mm",
          height: "1884 mm",
          wheelBase: "2900 mm",
          numberOfDoors: "5",
        },
        capacity: {
          fuelTank: "80 L",
          seatingCapacity: "7 seats",
          payload: "",
        },
        engine: {
          type: "2.0L Diesel Engine, 4 Cylinder 16 Valve",
          numberOfCylinders: "4",
          valveConfiguration: "",
          fuelSupplySystem: "",
          valvesPerCylinder: "4",
        },
        performance: {
          fuelType: "Diesel",
          power: "168 hp",
          rpmAtMaxPower: "3500 RPM",
          engineDisplacement: "1996 cc",
          torque: "405 Nm",
          rpmAtMaxTorque: "1750-2500 RPM",
        },
        steering: {
          powerSteering: "Yes",
          steeringColumn: "Adjustable",
          steeringGearType: "Rack & Pinion",
          adjustableSteeringColumn: "Yes",
          steeringType: "Electric Power",
        },
        suspension: {
          front: "Standard Duty",
          rear: "Standard Duty",
          shockAbsorbersType: "",
        },
        brakes: {
          front: "Ventilated Discs",
          rear: "Ventilated Discs",
        },
        transmission: {
          type: "Automatic",
          driveType: "4x2",
          gearBox: "6-Speed",
          steeringWheelGearshiftPaddle: "",
        },
        wheels: {
          alloyWheels: "Yes",
          wheelCovers: "No",
          alloyWheelSize: "20 Inch",
          wheelSize: "R20",
          spareTyreMaterial: "",
        },
        tyres: {
          size: "225/55 R20",
          type: "Radial",
          spareTyreSize: "",
        },
      },
      {
        variant: "2.0L Turbo Titanium Plus 4x2 AT",
        tier: "3",
        bodyType: "SUV",
        price: "₱2.259 Million",
        logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
        dimensions: {
          frontTread: "1620 mm",
          rearTread: "1620 mm",
          length: "4904 mm",
          width: "2201 mm",
          height: "1884 mm",
          wheelBase: "2900 mm",
          numberOfDoors: "5",
        },
        capacity: {
          fuelTank: "80 L",
          seatingCapacity: "7 seats",
          payload: "",
        },
        engine: {
          type: "2.0L Diesel Engine, 4 Cylinder 16 Valve",
          numberOfCylinders: "4",
          valveConfiguration: "",
          fuelSupplySystem: "",
          valvesPerCylinder: "4",
        },
        performance: {
          fuelType: "Diesel",
          power: "168 hp",
          rpmAtMaxPower: "3500 RPM",
          engineDisplacement: "1996 cc",
          torque: "405 Nm",
          rpmAtMaxTorque: "1750-2500 RPM",
        },
        steering: {
          powerSteering: "Yes",
          steeringColumn: "Adjustable",
          steeringGearType: "Rack & Pinion",
          adjustableSteeringColumn: "Yes",
          steeringType: "Electric Power",
        },
        suspension: {
          front: "Standard Duty",
          rear: "Standard Duty",
          shockAbsorbersType: "",
        },
        brakes: {
          front: "Ventilated Discs",
          rear: "Ventilated Discs",
        },
        transmission: {
          type: "Automatic",
          driveType: "4x2",
          gearBox: "6-Speed",
          steeringWheelGearshiftPaddle: "",
        },
        wheels: {
          alloyWheels: "Yes",
          wheelCovers: "No",
          alloyWheelSize: "20 Inch",
          wheelSize: "R20",
          spareTyreMaterial: "",
        },
        tyres: {
          size: "225/55 R20",
          type: "Radial",
          spareTyreSize: "",
        },
      },
      {
        variant: "2.0L Bi-Turbo Titanium Plus 4x4 AT",
        tier: "4",
        bodyType: "SUV",
        price: "₱2.555 Million",
        logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
        dimensions: {
          frontTread: "1620 mm",
          rearTread: "1620 mm",
          length: "4904 mm",
          width: "2201 mm",
          height: "1884 mm",
          wheelBase: "2900 mm",
          numberOfDoors: "5",
        },
        capacity: {
          fuelTank: "80 L",
          seatingCapacity: "7 seats",
          payload: "",
        },
        engine: {
          type: "2.0L Diesel Engine, 4 Cylinder 16 Valve",
          numberOfCylinders: "4",
          valveConfiguration: "",
          fuelSupplySystem: "",
          valvesPerCylinder: "4",
        },
        performance: {
          fuelType: "Diesel",
          power: "207 hp",
          rpmAtMaxPower: "3750 RPM",
          engineDisplacement: "1996 cc",
          torque: "500 Nm",
          rpmAtMaxTorque: "1750-2000 RPM",
        },
        steering: {
          powerSteering: "Yes",
          steeringColumn: "Adjustable",
          steeringGearType: "Rack & Pinion",
          adjustableSteeringColumn: "Yes",
          steeringType: "Electric Power",
        },
        suspension: {
          front: "Standard Duty",
          rear: "Standard Duty",
          shockAbsorbersType: "",
        },
        brakes: {
          front: "Ventilated Discs",
          rear: "Ventilated Discs",
        },
        transmission: {
          type: "Automatic",
          driveType: "4x4",
          gearBox: "10-Speed",
          steeringWheelGearshiftPaddle: "",
        },
        wheels: {
          alloyWheels: "Yes",
          wheelCovers: "No",
          alloyWheelSize: "20 Inch",
          wheelSize: "R20",
          spareTyreMaterial: "",
        },
        tyres: {
          size: "225/55 R20",
          type: "Radial",
          spareTyreSize: "",
        },
      },
      {
        variant: "Wildtrak 4x2",
        tier: "5",
        bodyType: "SUV",
        price: "₱2.439 Million                    Expected Price",
        logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
        dilogo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",mensions: {

          frontTread: "",
          rearTread: "",
          length: "4904 mm",
          width: "2201 mm",
          height: "1884 mm",
          wheelBase: "",
          numberOfDoors: "5",
        },
        capacity: {
          fuelTank: "",
          seatingCapacity: "7 seats",
          payload: "",
        },
        engine: {
          type: "2.0L Diesel Engine, 4 Cylinder 16 Valve",
          numberOfCylinders: "4",
          valveConfiguration: "",
          fuelSupplySystem: "",
          valvesPerCylinder: "4",
        },
        performance: {
          fuelType: "Diesel",
          power: "170 hp",
          rpmAtMaxPower: "3500 RPM",
          engineDisplacement: "1998 cc",
          torque: "405 Nm",
          rpmAtMaxTorque: "1750-2000 RPM",
        },
        steering: {
          powerSteering: "Yes",
          steeringColumn: "Adjustable",
          steeringGearType: "Rack & Pinion",
          adjustableSteeringColumn: "Yes",
          steeringType: "Power",
        },
        suspension: {
          front: "Double Wishbone",
          rear: "Torsion Beam",
          shockAbsorbersType: "",
        },
        brakes: {
          front: "Ventilated Discs",
          rear: "Discs",
        },
        transmission: {
          type: "Automatic",
          driveType: "4x2",
          gearBox: "6-Speed",
          steeringWheelGearshiftPaddle: "",
        },
        wheels: {
          alloyWheels: "Yes",
          wheelCovers: "No",
          alloyWheelSize: "20 Inch",
          wheelSize: "R20",
          spareTyreMaterial: "",
        },
        tyres: {
          size: "225/55 R20",
          type: "Radial",
          spareTyreSize: "",
        },
      },
    ],
  },
  {
    id: 3,
    name: "Ford Explorer",
    price: "P3,498,000 - P3,513,000",
    logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
    image:
      "https://d1hv7ee95zft1i.cloudfront.net/custom/car-model-photo/standard/ford-explorer-exterior-62f5f4125e8dc.jpg",
    bodyType: "SUV",
    variants: [
      {
        variant: "2.3L Limited EcoBoost",
        tier: "1",
        bodyType: "SUV",
        price: "₱3.498 Million",
        logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
        dimensions: {
          frontTread: "",
          rearTread: "",
          length: "5049 mm",
          width: "2268 mm",
          height: "1783 mm",
          wheelBase: "3025 mm",
          numberOfDoors: "5",
        },
        capacity: {
          fuelTank: "70 L",
          seatingCapacity: "7 seats",
          payload: "",
        },
        engine: {
          type: "2.3L Gasoline Engine, 4 Cylinder 16 Valve",
          numberOfCylinders: "4",
          valveConfiguration: "",
          fuelSupplySystem: "",
          valvesPerCylinder: "4",
        },
        performance: {
          fuelType: "Gasoline",
          power: "299 hp",
          rpmAtMaxPower: "5500 RPM",
          engineDisplacement: "2296 cc",
          torque: "420 Nm",
          rpmAtMaxTorque: "3500 RPM",
        },
        steering: {
          powerSteering: "Yes",
          steeringColumn: "Tilt & Telescopic",
          steeringGearType: "Rack & Pinion",
          adjustableSteeringColumn: "Yes",
          steeringType: "Electric Power",
        },
        suspension: {
          front: "MacPherson Strut",
          rear: "Multi-Link",
          shockAbsorbersType: "Coil Spring",
        },
        brakes: {
          front: "Discs",
          rear: "Discs",
        },
        transmission: {
          type: "Automatic",
          driveType: "4x4",
          gearBox: "10-Speed",
          steeringWheelGearshiftPaddle: "",
        },
        wheels: {
          alloyWheels: "Yes",
          wheelCovers: "No",
          alloyWheelSize: "20 Inch",
          wheelSize: "R20",
          spareTyreMaterial: "",
        },
        tyres: {
          size: "255/55 R20",
          type: "Radial",
          spareTyreSize: "",
        },
      },
    ],
  },
  {
    id: 4,
    name: "Ford Mustang",
    price: "P3,499,000 - P3,999,000",
    logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
    image:
      "https://d1hv7ee95zft1i.cloudfront.net/custom/car-model-photo/standard/ford-mustang-gt-premium-663b35673f292.jpg",
    bodyType: "Coupe",
    variants: [
      {
        variant: "2.3L Ecoboost",
        tier: "1",
        bodyType: "Coupe",
        price: "₱3.499 Million",
        logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
        dimensions: {
          frontTread: "",
          rearTread: "",
          length: "4811 mm",
          width: "2097 mm",
          height: "1407 mm",
          wheelBase: "2719 mm",
          numberOfDoors: "2",
        },
        capacity: {
          fuelTank: "",
          seatingCapacity: "4 seats",
          payload: "",
        },
        engine: {
          type: "2.3L Gasoline Engine, 4 Cylinder 16 Valve",
          numberOfCylinders: "4",
          valveConfiguration: "",
          fuelSupplySystem: "",
          valvesPerCylinder: "4",
        },
        performance: {
          fuelType: "Gasoline",
          power: "315 hp",
          rpmAtMaxPower: "5500 RPM",
          engineDisplacement: "2298 cc",
          torque: "475 Nm",
          rpmAtMaxTorque: "3000 RPM",
        },
        steering: {
          powerSteering: "Yes",
          steeringColumn: "Tilt & Telescopic",
          steeringGearType: "Rack & Pinion",
          adjustableSteeringColumn: "Yes",
          steeringType: "Electric Power",
        },
        suspension: {
          front: "MacPherson Strut",
          rear: "Multi-Link",
          shockAbsorbersType: "Coil Spring",
        },
        brakes: {
          front: "Discs",
          rear: "Discs",
        },
        transmission: {
          type: "Automatic",
          driveType: "RWD",
          gearBox: "10-Speed",
          steeringWheelGearshiftPaddle: "Yes",
        },
        wheels: {
          alloyWheels: "Yes",
          wheelCovers: "No",
          alloyWheelSize: "19 Inch",
          wheelSize: "ZR19",
          spareTyreMaterial: "",
        },
        tyres: {
          size: "255/40 ZR19",
          type: "Runflat",
          spareTyreSize: "",
        },
      },
      {
        variant: "5.0L GT Premium V8",
        tier: "2",
        bodyType: "Coupe",
        price: "₱3.999 Million",
        logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
        dimensions: {
          frontTread: "",
          rearTread: "",
          length: "4811 mm",
          width: "2097 mm",
          height: "1414 mm",
          wheelBase: "2719 mm",
          numberOfDoors: "2",
        },
        capacity: {
          fuelTank: "",
          seatingCapacity: "4 seats",
          payload: "",
        },
        engine: {
          type: "5.0L Gasoline Engine, 8 Cylinder 32 Valve",
          numberOfCylinders: "8",
          valveConfiguration: "",
          fuelSupplySystem: "",
          valvesPerCylinder: "4",
        },
        performance: {
          fuelType: "Gasoline",
          power: "486 hp",
          rpmAtMaxPower: "7250 RPM",
          engineDisplacement: "4998 cc",
          torque: "567 Nm",
          rpmAtMaxTorque: "4850 RPM",
        },
        steering: {
          powerSteering: "Yes",
          steeringColumn: "Tilt & Telescopic",
          steeringGearType: "Rack & Pinion",
          adjustableSteeringColumn: "Yes",
          steeringType: "Electric Power",
        },
        suspension: {
          front: "MacPherson Strut",
          rear: "Multi-Link",
          shockAbsorbersType: "Coil Spring",
        },
        brakes: {
          front: "Discs",
          rear: "Discs",
        },
        transmission: {
          type: "Automatic",
          driveType: "RWD",
          gearBox: "10-Speed",
          steeringWheelGearshiftPaddle: "Yes",
        },
        wheels: {
          alloyWheels: "Yes",
          wheelCovers: "No",
          alloyWheelSize: "19 Inch",
          wheelSize: "R19",
          spareTyreMaterial: "",
        },
        tyres: {
          size: "255/40 R19",
          type: "Radial",
          spareTyreSize: "",
        },
      },
    ],
  },
  {
    id: 5,
    name: "Ford Ranger",
    price: "P1,259,000 - P1,955,000",
    logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
    image:
      "https://d1hv7ee95zft1i.cloudfront.net/custom/car-model-photo/standard/exterior-6671441369bb0.jpg",
    bodyType: "Pickup Trucks",
    variants: [
      {
        variant: "2.0L Turbo XL 4x4 MT",
        tier: "1",
        bodyType: "Pickup Trucks",
        price: "₱1.259 Million",
        logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
        dimensions: {
          frontTread: "1620 mm",
          rearTread: "1620 mm",
          length: "5370 mm",
          width: "1918 mm",
          height: "1884 mm",
          wheelBase: "3270 mm",
          numberOfDoors: "4",
        },
        capacity: {
          fuelTank: "80 L",
          seatingCapacity: "5 seats",
          payload: "",
        },
        engine: {
          type: "2.0L Diesel Engine, 4 Cylinder 16 Valve",
          numberOfCylinders: "4",
          valveConfiguration: "",
          fuelSupplySystem: "",
          valvesPerCylinder: "4",
        },
        performance: {
          fuelType: "Diesel",
          power: "168 hp",
          rpmAtMaxPower: "3500 RPM",
          engineDisplacement: "1996 cc",
          torque: "405 Nm",
          rpmAtMaxTorque: "1750-2500 RPM",
        },
        steering: {
          powerSteering: "Yes",
          steeringColumn: "Adjustable",
          steeringGearType: "Rack & Pinion",
          adjustableSteeringColumn: "Yes",
          steeringType: "Power",
        },
        suspension: {
          front: "Double Wishbone",
          rear: "Leaf Springs",
          shockAbsorbersType: "Coil Spring",
        },
        brakes: {
          front: "Ventilated Discs",
          rear: "Drums",
        },
        transmission: {
          type: "Manual",
          driveType: "4x4",
          gearBox: "6-Speed",
          steeringWheelGearshiftPaddle: "",
        },
        wheels: {
          alloyWheels: "Yes",
          wheelCovers: "Yes",
          alloyWheelSize: "16 Inch",
          wheelSize: "",
          spareTyreMaterial: "Steel",
        },
        tyres: {
          size: "255/70 R16",
          type: "Radial",
          spareTyreSize: "255/70 R16",
        },
      },
      {
        variant: "2.0L Turbo XLT 4x2 AT",
        tier: "2",
        bodyType: "Pickup Trucks",
        price: "₱1.389 Million",
        logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
        dimensions: {
          frontTread: "1620 mm",
          rearTread: "1620 mm",
          length: "5370 mm",
          width: "1918 mm",
          height: "1884 mm",
          wheelBase: "3270 mm",
          numberOfDoors: "4",
        },
        capacity: {
          fuelTank: "80 L",
          seatingCapacity: "5 seats",
          payload: "",
        },
        engine: {
          type: "2.0L Diesel Engine, 4 Cylinder 16 Valve",
          numberOfCylinders: "4",
          valveConfiguration: "",
          fuelSupplySystem: "",
          valvesPerCylinder: "4",
        },
        performance: {
          fuelType: "Diesel",
          power: "168 hp",
          rpmAtMaxPower: "3500 RPM",
          engineDisplacement: "1996 cc",
          torque: "405 Nm",
          rpmAtMaxTorque: "1750-2500 RPM",
        },
        steering: {
          powerSteering: "Yes",
          steeringColumn: "Adjustable",
          steeringGearType: "Rack & Pinion",
          adjustableSteeringColumn: "Yes",
          steeringType: "Power",
        },
        suspension: {
          front: "Double Wishbone",
          rear: "Leaf Springs",
          shockAbsorbersType: "Coil Spring",
        },
        brakes: {
          front: "Ventilated Discs",
          rear: "Drums",
        },
        transmission: {
          type: "Automatic",
          driveType: "4x2",
          gearBox: "6-Speed",
          steeringWheelGearshiftPaddle: "",
        },
        wheels: {
          alloyWheels: "Yes",
          wheelCovers: "No",
          alloyWheelSize: "17 Inch",
          wheelSize: "R17",
          spareTyreMaterial: "Alloy",
        },
        tyres: {
          size: "255/70 R17",
          type: "Radial",
          spareTyreSize: "255/70 R17",
        },
      },
      {
        variant: "2.0L Turbo Sport 4x2 AT",
        tier: "3",
        bodyType: "Pickup Trucks",
        price: "₱1.504 Million",
        logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
        dimensions: {
          frontTread: "1620 mm",
          rearTread: "1620 mm",
          length: "5370 mm",
          width: "1918 mm",
          height: "1884 mm",
          wheelBase: "3270 mm",
          numberOfDoors: "4",
        },
        capacity: {
          fuelTank: "80 L",
          seatingCapacity: "5 seats",
          payload: "",
        },
        engine: {
          type: "2.0L Diesel Engine, 4 Cylinder 16 Valve",
          numberOfCylinders: "4",
          valveConfiguration: "",
          fuelSupplySystem: "",
          valvesPerCylinder: "4",
        },
        performance: {
          fuelType: "Diesel",
          power: "168 hp",
          rpmAtMaxPower: "3500 RPM",
          engineDisplacement: "1996 cc",
          torque: "405 Nm",
          rpmAtMaxTorque: "1750-2500 RPM",
        },
        steering: {
          powerSteering: "Yes",
          steeringColumn: "Adjustable",
          steeringGearType: "Rack & Pinion",
          adjustableSteeringColumn: "Yes",
          steeringType: "Power",
        },
        suspension: {
          front: "Double Wishbone",
          rear: "Leaf Springs",
          shockAbsorbersType: "Coil Spring",
        },
        brakes: {
          front: "Ventilated Discs",
          rear: "Drums",
        },
        transmission: {
          type: "Automatic",
          driveType: "4x2",
          gearBox: "6-Speed",
          steeringWheelGearshiftPaddle: "",
        },
        wheels: {
          alloyWheels: "Yes",
          wheelCovers: "No",
          alloyWheelSize: "18 Inch",
          wheelSize: "R18",
          spareTyreMaterial: "Alloy",
        },
        tyres: {
          size: "255/65 R18",
          type: "Radial",
          spareTyreSize: "255/65 R18",
        },
      },
      {
        variant: "2.0L Turbo Wildtrak 4x2 AT",
        tier: "4",
        bodyType: "Pickup Trucks",
        price: "₱1.614 Million",
        logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
        dimensions: {
          frontTread: "1620 mm",
          rearTread: "1620 mm",
          length: "5370 mm",
          width: "1918 mm",
          height: "1884 mm",
          wheelBase: "3270 mm",
          numberOfDoors: "4",
        },
        capacity: {
          fuelTank: "80 L",
          seatingCapacity: "5 seats",
          payload: "",
        },
        engine: {
          type: "2.0L Diesel Engine, 4 Cylinder 16 Valve",
          numberOfCylinders: "4",
          valveConfiguration: "",
          fuelSupplySystem: "",
          valvesPerCylinder: "4",
        },
        performance: {
          fuelType: "Diesel",
          power: "168 hp",
          rpmAtMaxPower: "3500 RPM",
          engineDisplacement: "1996 cc",
          torque: "405 Nm",
          rpmAtMaxTorque: "1750-2500 RPM",
        },
        steering: {
          powerSteering: "Yes",
          steeringColumn: "Adjustable",
          steeringGearType: "Rack & Pinion",
          adjustableSteeringColumn: "Yes",
          steeringType: "Power",
        },
        suspension: {
          front: "Double Wishbone",
          rear: "Leaf Springs",
          shockAbsorbersType: "Coil Spring",
        },
        brakes: {
          front: "Ventilated Discs",
          rear: "Discs",
        },
        transmission: {
          type: "Automatic",
          driveType: "4x2",
          gearBox: "6-Speed",
          steeringWheelGearshiftPaddle: "",
        },
        wheels: {
          alloyWheels: "Yes",
          wheelCovers: "No",
          alloyWheelSize: "18 Inch",
          wheelSize: "R18",
          spareTyreMaterial: "Alloy",
        },
        tyres: {
          size: "255/65 R18",
          type: "Radial",
          spareTyreSize: "255/65 R18",
        },
      },
      {
        variant: "2.0L Turbo Sport 4x4 AT",
        tier: "5",
        bodyType: "Pickup Trucks",
        price: "₱1.624 Million",
        logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
        dimensions: {
          frontTread: "1620 mm",
          rearTread: "1620 mm",
          length: "5370 mm",
          width: "1918 mm",
          height: "1884 mm",
          wheelBase: "3270 mm",
          numberOfDoors: "4",
        },
        capacity: {
          fuelTank: "80 L",
          seatingCapacity: "5 seats",
          payload: "",
        },
        engine: {
          type: "2.0L Diesel Engine, 4 Cylinder 16 Valve",
          numberOfCylinders: "4",
          valveConfiguration: "",
          fuelSupplySystem: "",
          valvesPerCylinder: "4",
        },
        performance: {
          fuelType: "Diesel",
          power: "168 hp",
          rpmAtMaxPower: "3500 RPM",
          engineDisplacement: "1996 cc",
          torque: "405 Nm",
          rpmAtMaxTorque: "1750-2500 RPM",
        },
        steering: {
          powerSteering: "Yes",
          steeringColumn: "Adjustable",
          steeringGearType: "Rack & Pinion",
          adjustableSteeringColumn: "Yes",
          steeringType: "Power",
        },
        suspension: {
          front: "Double Wishbone",
          rear: "Leaf Springs",
          shockAbsorbersType: "Coil Spring",
        },
        brakes: {
          front: "Ventilated Discs",
          rear: "Drums",
        },
        transmission: {
          type: "Automatic",
          driveType: "4x4",
          gearBox: "6-Speed",
          steeringWheelGearshiftPaddle: "",
        },
        wheels: {
          alloyWheels: "Yes",
          wheelCovers: "No",
          alloyWheelSize: "18 Inch",
          wheelSize: "R18",
          spareTyreMaterial: "Alloy",
        },
        tyres: {
          size: "255/65 R18",
          type: "Radial",
          spareTyreSize: "255/65 R18",
        },
      },
      {
        variant: "2.0L Bi-Turbo Wildtrak 4x4 AT",
        tier: "6",
        bodyType: "Pickup Trucks",
        price: "₱1.94 Million",
        logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
        dimensions: {
          frontTread: "1620 mm",
          rearTread: "1620 mm",
          length: "5370 mm",
          width: "1918 mm",
          height: "1884 mm",
          wheelBase: "3270 mm",
          numberOfDoors: "4",
        },
        capacity: {
          fuelTank: "80 L",
          seatingCapacity: "5 seats",
          payload: "",
        },
        engine: {
          type: "2.0L Diesel Engine, 4 Cylinder 16 Valve",
          numberOfCylinders: "4",
          valveConfiguration: "",
          fuelSupplySystem: "",
          valvesPerCylinder: "4",
        },
        performance: {
          fuelType: "Diesel",
          power: "207 hp",
          rpmAtMaxPower: "3750 RPM",
          engineDisplacement: "1996 cc",
          torque: "500 Nm",
          rpmAtMaxTorque: "1750-2000 RPM",
        },
        steering: {
          powerSteering: "Yes",
          steeringColumn: "Adjustable",
          steeringGearType: "Rack & Pinion",
          adjustableSteeringColumn: "Yes",
          steeringType: "Power",
        },
        suspension: {
          front: "Double Wishbone",
          rear: "Leaf Springs",
          shockAbsorbersType: "Coil Spring",
        },
        brakes: {
          front: "Ventilated Discs",
          rear: "Discs",
        },
        transmission: {
          type: "Automatic",
          driveType: "4x4",
          gearBox: "10-Speed",
          steeringWheelGearshiftPaddle: "",
        },
        wheels: {
          alloyWheels: "Yes",
          wheelCovers: "No",
          alloyWheelSize: "18 Inch",
          wheelSize: "R18",
          spareTyreMaterial: "Alloy",
        },
        tyres: {
          size: "255/65 R18",
          type: "Radial",
          spareTyreSize: "255/65 R18",
        },
      },
    ],
  },
  {
    id: 6,
    name: "Ford Ranger Raptor",
    price: "P2,345,000 - P2,360,000",
    logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
    image:
      "https://d1hv7ee95zft1i.cloudfront.net/custom/car-model-photo/standard/ranger-raptor-primary-64f191d78c8c3.jpg",
    bodyType: "Pickup Trucks",
    variants: [
      {
        variant: "2.0L Bi-Turbo 4WD",
        tier: "1",
        bodyType: "Pickup Trucks",
        price: "₱2.345 Million",
        logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
        dimensions: {
          frontTread: "",
          rearTread: "",
          length: "5381 mm",
          width: "2028 mm",
          height: "1922 mm",
          wheelBase: "3270 mm",
          numberOfDoors: "4",
        },
        capacity: {
          fuelTank: "",
          seatingCapacity: "5 seats",
          payload: "",
        },
        engine: {
          type: "2.0L Diesel Engine, 4 Cylinder 16 Valve",
          numberOfCylinders: "4",
          valveConfiguration: "",
          fuelSupplySystem: "",
          valvesPerCylinder: "4",
        },
        performance: {
          fuelType: "Diesel",
          power: "208 hp",
          rpmAtMaxPower: "3750 RPM",
          engineDisplacement: "1996 cc",
          torque: "500 Nm",
          rpmAtMaxTorque: "1750-2000 RPM",
        },
        steering: {
          powerSteering: "Yes",
          steeringColumn: "Adjustable",
          steeringGearType: "Rack & Pinion",
          adjustableSteeringColumn: "Yes",
          steeringType: "Electric Power",
        },
        suspension: {
          front: "Double Wishbone",
          rear: "Coil Spring",
          shockAbsorbersType: "",
        },
        brakes: {
          front: "Ventilated Discs",
          rear: "Discs",
        },
        transmission: {
          type: "Automatic",
          driveType: "4x4",
          gearBox: "10-Speed",
          steeringWheelGearshiftPaddle: "Yes",
        },
        wheels: {
          alloyWheels: "Yes",
          wheelCovers: "No",
          alloyWheelSize: "17 Inch",
          wheelSize: "R17",
          spareTyreMaterial: "",
        },
        tyres: {
          size: "285/70 R17",
          type: "Radial",
          spareTyreSize: "",
        },
      },
    ],
  },
  {
    id: 7,
    name: "Ford Territory",
    price: "P1,335,000 - P1,625,000",
    logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
    image:
      "https://d1hv7ee95zft1i.cloudfront.net/custom/car-model-photo/standard/ford-territory-titanium-x-exterior-65adf719401a5.jpg",
    bodyType: "SUV",
    variants: [
      {
        variant: "Titanium",
        tier: "1",
        bodyType: "SUV",
        price: "₱1.335 Million",
        logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
        dimensions: {
          frontTread: "",
          rearTread: "",
          length: "4630 mm",
          width: "1935 mm",
          height: "1706 mm",
          wheelBase: "2726 mm",
          numberOfDoors: "5",
        },
        capacity: {
          fuelTank: "60 L",
          seatingCapacity: "5 seats",
          payload: "",
        },
        engine: {
          type: "1.5L Gasoline Engine, 4 Cylinder 16 Valve",
          numberOfCylinders: "4",
          valveConfiguration: "",
          fuelSupplySystem: "",
          valvesPerCylinder: "4",
        },
        performance: {
          fuelType: "Gasoline",
          power: "160 hp",
          rpmAtMaxPower: "",
          engineDisplacement: "1499 cc",
          torque: "248 Nm",
          rpmAtMaxTorque: "",
        },
        steering: {
          powerSteering: "Yes",
          steeringColumn: "Tilt & Telescopic",
          steeringGearType: "Rack & Pinion",
          adjustableSteeringColumn: "Yes",
          steeringType: "Electric Power",
        },
        suspension: {
          front: "MacPherson Strut",
          rear: "Multi-Link",
          shockAbsorbersType: "",
        },
        brakes: {
          front: "Ventilated Discs",
          rear: "Discs",
        },
        transmission: {
          type: "Automatic",
          driveType: "",
          gearBox: "7-Speed",
          steeringWheelGearshiftPaddle: "",
        },
        wheels: {
          alloyWheels: "Yes",
          wheelCovers: "No",
          alloyWheelSize: "18 Inch",
          wheelSize: "R18",
          spareTyreMaterial: "",
        },
        tyres: {
          size: "235/55 R18",
          type: "Radial",
          spareTyreSize: "",
        },
      },
      {
        variant: "Titanium X",
        tier: "2",
        bodyType: "SUV",
        price: "₱1.599 Million",
        logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
        dimensions: {
          frontTread: "",
          rearTread: "",
          length: "4630 mm",
          width: "1935 mm",
          height: "1706 mm",
          wheelBase: "2726 mm",
          numberOfDoors: "5",
        },
        capacity: {
          fuelTank: "60 L",
          seatingCapacity: "5 seats",
          payload: "",
        },
        engine: {
          type: "1.5L Gasoline Engine, 4 Cylinder 16 Valve",
          numberOfCylinders: "4",
          valveConfiguration: "",
          fuelSupplySystem: "",
          valvesPerCylinder: "4",
        },
        performance: {
          fuelType: "Gasoline",
          power: "160 hp",
          rpmAtMaxPower: "",
          engineDisplacement: "1499 cc",
          torque: "248 Nm",
          rpmAtMaxTorque: "",
        },
        steering: {
          powerSteering: "Yes",
          steeringColumn: "Tilt & Telescopic",
          steeringGearType: "Rack & Pinion",
          adjustableSteeringColumn: "Yes",
          steeringType: "Electric Power",
        },
        suspension: {
          front: "MacPherson Strut",
          rear: "Multi-Link",
          shockAbsorbersType: "",
        },
        brakes: {
          front: "Ventilated Discs",
          rear: "Discs",
        },
        transmission: {
          type: "Automatic",
          driveType: "",
          gearBox: "7-Speed",
          steeringWheelGearshiftPaddle: "",
        },
        wheels: {
          alloyWheels: "Yes",
          wheelCovers: "No",
          alloyWheelSize: "19 Inch",
          wheelSize: "R19",
          spareTyreMaterial: "",
        },
        tyres: {
          size: "235/50 R19",
          type: "Radial",
          spareTyreSize: "",
        },
      },
      {
        variant: "Sport",
        tier: "3",
        bodyType: "SUV",
        price: "₱1.625 Million",
        logo: "https://d1hv7ee95zft1i.cloudfront.net/custom/car-make/original/ford-64f1953507e77.png",
        dimensions: {
          frontTread: "",
          rearTread: "",
          length: "4630 mm",
          width: "1935 mm",
          height: "1706 mm",
          wheelBase: "2726 mm",
          numberOfDoors: "5",
        },
        capacity: {
          fuelTank: "60 L",
          seatingCapacity: "5 seats",
          payload: "",
        },
        engine: {
          type: "1.5L Gasoline Engine, 4 Cylinder 16 Valve",
          numberOfCylinders: "4",
          valveConfiguration: "",
          fuelSupplySystem: "",
          valvesPerCylinder: "4",
        },
        performance: {
          fuelType: "Gasoline",
          power: "160 hp",
          rpmAtMaxPower: "",
          engineDisplacement: "1499 cc",
          torque: "248 Nm",
          rpmAtMaxTorque: "",
        },
        steering: {
          powerSteering: "Yes",
          steeringColumn: "Tilt & Telescopic",
          steeringGearType: "Rack & Pinion",
          adjustableSteeringColumn: "Yes",
          steeringType: "Electric Power",
        },
        suspension: {
          front: "MacPherson Strut",
          rear: "Multi-Link",
          shockAbsorbersType: "",
        },
        brakes: {
          front: "Ventilated Discs",
          rear: "Discs",
        },
        transmission: {
          type: "Dual Clutch",
          driveType: "",
          gearBox: "7-Speed",
          steeringWheelGearshiftPaddle: "",
        },
        wheels: {
          alloyWheels: "Yes",
          wheelCovers: "No",
          alloyWheelSize: "19 Inch",
          wheelSize: "R19",
          spareTyreMaterial: "",
        },
        tyres: {
          size: "235/50 R19",
          type: "Radial",
          spareTyreSize: "",
        },
      },
    ],
  },
];

module.exports = ford;
